analytics: {}
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.671452
  lightness: 0.118243
  rhythmicContrast: 0.579391
  saturation: 0.550675
cta: {}
layout_spectrum: 0.40894724561857654
name: YaoBoLu
opengraph: {}
purpose: {}
typography_spectrum: 0.635254
