analytics: {}
color:
  brandColors:
    - '#B0C0B8'
    - '#005888'
    - '#808070'
    - '#48A0D8'
    - '#A0C8E0'
  brandStrength: 0.671452
  lightness: 0.118243
  rhythmicContrast: 0.579391
  saturation: 0.550675
cta: {}
layout_spectrum: 0.98902
name: Yao Bo Lu
opengraph: {}
purpose: {}
typography_spectrum: 0.635254
